In [ ]:
# context: Piknik returned a large CSV with web3 metadata to be enriched in the stac json
# from the old (pre-processing) first-year landsat 9 scenes

In [1]:
# load csv
import pandas as pd

In [4]:
# this is the file metadata that in deal making at PikNik
metadata_csv = pd.read_csv(
    "../../../data/data_safe/University of Maryland - Landsat9 Metadata.csv",
    header=None,
    names=["FileCID", "Filepath", "PieceCID"],
)

metadata_csv.head()

In [5]:
# Create a sample DataFrame and extract key information
df = metadata_csv

In [6]:
# If you also want to keep 'filename' as a separate column
df["filename"] = df["Filepath"].apply(lambda x: x.split("/")[-1])
df["sceneid"] = df["Filepath"].apply(lambda x: x.split("/")[-2])
# Display the DataFrame
df

,FileCID,Filepath,PieceCID,filename,sceneid
0,bafybeihp3kfzczydawevi2nfhbcwoqx74audj3cq3ka5f...,buckets/uofm-data1/landsat9-c2-l1/20220223/LC0...,baga6ea4seaqjq7aohp5hxo33c2pr4huhotnp26adejnc4...,LC09_L1TP_178078_20220223_20220223_02_T1_B3.TIF,LC09_L1TP_178078_20220223_20220223_02_T1
1,bafybeiamauzxknzyo3fizojnx3fibsgadox4see5mcb6q...,buckets/uofm-data1/landsat9-c2-l1/20220223/LC0...,baga6ea4seaqi5rzk5j4jx4uarvdgyqifjjoayw5ymxylf...,LC09_L1TP_178077_20220223_20220223_02_T1_B8.TIF,LC09_L1TP_178077_20220223_20220223_02_T1
2,bafybeifjx3gv26h23ndj66uaqdoafaxuxngh5gossas6m...,buckets/uofm-data1/landsat9-c2-l1/20211212/LC0...,baga6ea4seaqmkjznqjkgbqyjf5sxuy2mhbjhjr46c3ey6...,LC09_L1GT_163118_20211212_20220120_02_T2_SZA.TIF,LC09_L1GT_163118_20211212_20220120_02_T2
3,bafybeig2dl4kwrkp2it6bihstkh5pq33spz3owizyw7zj...,buckets/uofm-data1/landsat9-c2-l1/20220223/LC0...,baga6ea4seaqazvl3fpomzeveths64xaxyf3vccuhnlc6d...,LC09_L1TP_178043_20220223_20220223_02_T1_B9.TIF,LC09_L1TP_178043_20220223_20220223_02_T1
4,bafkreidliycdctu2ix7db5f3f6qobjuuvbedfluz6txmq...,buckets/uofm-data1/landsat9-c2-l1/20220223/LC0...,baga6ea4seaqoenlw2rutoowhcllgzd3f6wpipfptijvhr...,LC09_L1TP_178035_20220223_20220223_02_T1_MTL.json,LC09_L1TP_178035_20220223_20220223_02_T1
...,...,...,...,...,...
4828490,bafkreihk3fo534sveamikg2bgpe7vcx3ylhoicdw5yefp...,buckets/uofm-data1/landsat9-c2-l1/20220223/LC0...,baga6ea4seaqoenlw2rutoowhcllgzd3f6wpipfptijvhr...,LC09_L1TP_178077_20220223_20220223_02_T1_MTL.txt,LC09_L1TP_178077_20220223_20220223_02_T1
4828491,bafybeic3fjcf2lnh6362kcsiqeqryzjkrbv5jhmd5cqr2...,buckets/uofm-data1/landsat9-c2-l1/20211212/LC0...,baga6ea4seaqmkjznqjkgbqyjf5sxuy2mhbjhjr46c3ey6...,LC09_L1GT_179023_20211212_20220123_02_T2_QA_PI...,LC09_L1GT_179023_20211212_20220123_02_T2
4828492,bafybeib4obckcc4zdf3vjndbcktf3id7hqjvskg3ejok2...,buckets/uofm-data1/landsat9-c2-l1/20220223/LC0...,baga6ea4seaqk2qlu243yup2xh7hqhfcr7ithyhi2ncan7...,LC09_L1TP_178077_20220223_20220223_02_T1_B1.TIF,LC09_L1TP_178077_20220223_20220223_02_T1
4828493,bafybeigm2nhm5m6grpuygvnubsz5wrqixeglbv3k7nkys...,buckets/uofm-data1/landsat9-c2-l1/20220223/LC0...,baga6ea4seaqfaqfxihjp3jp3ts74g3dijwt46eit4zwjf...,LC09_L1TP_178077_20220223_20220223_02_T1_B4.TIF,LC09_L1TP_178077_20220223_20220223_02_T1
4828494,bafkreicjw3oeg5ojqrigxh3v3ycqm6vw7bre7z3dfbbjq...,buckets/uofm-data1/landsat9-c2-l1/20220223/LC0...,baga6ea4seaqoenlw2rutoowhcllgzd3f6wpipfptijvhr...,LC09_L1TP_178076_20220223_20220223_02_T1_stac....,LC09_L1TP_178076_20220223_20220223_02_T1

In [7]:
# Try just matching any 3 digits for each field.
regex_pattern = r"^.{10}(?P<PPP>\d{3})(?P<RRR>\d{3})_(?P<AcqDate>\d{8})_(?P<PrsDate>\d{8})_.{2}_.{2}_(?P<Asset>[^\.]+\..+)"
df_extracted = df["filename"].str.extract(regex_pattern)
df_extracted

         PPP  RRR   AcqDate   PrsDate         Asset
0        178  078  20220223  20220223        B3.TIF
1        178  077  20220223  20220223        B8.TIF
2        163  118  20211212  20220120       SZA.TIF
3        178  043  20220223  20220223        B9.TIF
4        178  035  20220223  20220223      MTL.json
...      ...  ...       ...       ...           ...
4828490  178  077  20220223  20220223       MTL.txt
4828491  179  023  20211212  20220123  QA_PIXEL.TIF
4828492  178  077  20220223  20220223        B1.TIF
4828493  178  077  20220223  20220223        B4.TIF
4828494  178  076  20220223  20220223     stac.json

[4828495 rows x 5 columns]

In [8]:
df = pd.concat([df, df_extracted], axis=1)
df

,FileCID,Filepath,PieceCID,filename,sceneid,PPP,RRR,AcqDate,PrsDate,Asset
0,bafybeihp3kfzczydawevi2nfhbcwoqx74audj3cq3ka5f...,buckets/uofm-data1/landsat9-c2-l1/20220223/LC0...,baga6ea4seaqjq7aohp5hxo33c2pr4huhotnp26adejnc4...,LC09_L1TP_178078_20220223_20220223_02_T1_B3.TIF,LC09_L1TP_178078_20220223_20220223_02_T1,178,078,20220223,20220223,B3.TIF
1,bafybeiamauzxknzyo3fizojnx3fibsgadox4see5mcb6q...,buckets/uofm-data1/landsat9-c2-l1/20220223/LC0...,baga6ea4seaqi5rzk5j4jx4uarvdgyqifjjoayw5ymxylf...,LC09_L1TP_178077_20220223_20220223_02_T1_B8.TIF,LC09_L1TP_178077_20220223_20220223_02_T1,178,077,20220223,20220223,B8.TIF
2,bafybeifjx3gv26h23ndj66uaqdoafaxuxngh5gossas6m...,buckets/uofm-data1/landsat9-c2-l1/20211212/LC0...,baga6ea4seaqmkjznqjkgbqyjf5sxuy2mhbjhjr46c3ey6...,LC09_L1GT_163118_20211212_20220120_02_T2_SZA.TIF,LC09_L1GT_163118_20211212_20220120_02_T2,163,118,20211212,20220120,SZA.TIF
3,bafybeig2dl4kwrkp2it6bihstkh5pq33spz3owizyw7zj...,buckets/uofm-data1/landsat9-c2-l1/20220223/LC0...,baga6ea4seaqazvl3fpomzeveths64xaxyf3vccuhnlc6d...,LC09_L1TP_178043_20220223_20220223_02_T1_B9.TIF,LC09_L1TP_178043_20220223_20220223_02_T1,178,043,20220223,20220223,B9.TIF
4,bafkreidliycdctu2ix7db5f3f6qobjuuvbedfluz6txmq...,buckets/uofm-data1/landsat9-c2-l1/20220223/LC0...,baga6ea4seaqoenlw2rutoowhcllgzd3f6wpipfptijvhr...,LC09_L1TP_178035_20220223_20220223_02_T1_MTL.json,LC09_L1TP_178035_20220223_20220223_02_T1,178,035,20220223,20220223,MTL.json
...,...,...,...,...,...,...,...,...,...,...
4828490,bafkreihk3fo534sveamikg2bgpe7vcx3ylhoicdw5yefp...,buckets/uofm-data1/landsat9-c2-l1/20220223/LC0...,baga6ea4seaqoenlw2rutoowhcllgzd3f6wpipfptijvhr...,LC09_L1TP_178077_20220223_20220223_02_T1_MTL.txt,LC09_L1TP_178077_20220223_20220223_02_T1,178,077,20220223,20220223,MTL.txt
4828491,bafybeic3fjcf2lnh6362kcsiqeqryzjkrbv5jhmd5cqr2...,buckets/uofm-data1/landsat9-c2-l1/20211212/LC0...,baga6ea4seaqmkjznqjkgbqyjf5sxuy2mhbjhjr46c3ey6...,LC09_L1GT_179023_20211212_20220123_02_T2_QA_PI...,LC09_L1GT_179023_20211212_20220123_02_T2,179,023,20211212,20220123,QA_PIXEL.TIF
4828492,bafybeib4obckcc4zdf3vjndbcktf3id7hqjvskg3ejok2...,buckets/uofm-data1/landsat9-c2-l1/20220223/LC0...,baga6ea4seaqk2qlu243yup2xh7hqhfcr7ithyhi2ncan7...,LC09_L1TP_178077_20220223_20220223_02_T1_B1.TIF,LC09_L1TP_178077_20220223_20220223_02_T1,178,077,20220223,20220223,B1.TIF
4828493,bafybeigm2nhm5m6grpuygvnubsz5wrqixeglbv3k7nkys...,buckets/uofm-data1/landsat9-c2-l1/20220223/LC0...,baga6ea4seaqfaqfxihjp3jp3ts74g3dijwt46eit4zwjf...,LC09_L1TP_178077_20220223_20220223_02_T1_B4.TIF,LC09_L1TP_178077_20220223_20220223_02_T1,178,077,20220223,20220223,B4.TIF
4828494,bafkreicjw3oeg5ojqrigxh3v3ycqm6vw7bre7z3dfbbjq...,buckets/uofm-data1/landsat9-c2-l1/20220223/LC0...,baga6ea4seaqoenlw2rutoowhcllgzd3f6wpipfptijvhr...,LC09_L1TP_178076_20220223_20220223_02_T1_stac....,LC09_L1TP_178076_20220223_20220223_02_T1,178,076,20220223,20220223,stac.json

In [9]:
# select scenes for cont-US

In [10]:
import geopandas as gpd

In [11]:
cont_us = gpd.read_file(
    "../../../web3-geo-dashboard/data_processing/landsat_scenes_intersecting_continential_us.geojson"
)

In [12]:
cont_us["PPP"] = cont_us["PATH"].astype(str).str.zfill(3)
cont_us["RRR"] = cont_us["ROW"].astype(str).str.zfill(3)

In [13]:
row_path_dedup = cont_us[["PPP", "RRR"]].drop_duplicates()

In [17]:
cont_us_all = df.merge(row_path_dedup, on=["PPP", "RRR"], how="inner")

In [20]:
len(cont_us_all.sceneid.unique())

8069

In [22]:
cont_us_all.to_csv("../../../data/data_safe/L9_us_cont_scenes_piknik.csv", index=False)

## Band 5 only

In [15]:
cont_us_B5 = df.merge(row_path_dedup, on=["PPP", "RRR"], how="inner").query(
    'Asset=="B5.TIF"'
)

In [16]:
cont_us_B5.query('RRR=="028"').drop_duplicates(subset=["PPP", "RRR"])

,FileCID,Filepath,PieceCID,filename,sceneid,PPP,RRR,AcqDate,PrsDate,Asset
1299,bafybeieyjpwbkijryiybak3f5mth5aofxogsowcn67kej...,buckets/uofm-data1/landsat9-c2-l1/20211103/LC0...,baga6ea4seaqkfozzvnmaoasorcco6e73dv5iasiyppjk6...,LC09_L1TP_023028_20211103_20220118_02_T1_B5.TIF,LC09_L1TP_023028_20211103_20220118_02_T1,023,028,20211103,20220118,B5.TIF
2160,bafybeibpp6ie2eafq24nqtc62665f3e3vue56db4na3lx...,buckets/uofm-data1/landsat9-c2-l1/20211103/LC0...,baga6ea4seaqfrkqhtmxcpolq542avgqqc4xpxysjlyitq...,LC09_L1TP_039028_20211103_20220118_02_T1_B5.TIF,LC09_L1TP_039028_20211103_20220118_02_T1,039,028,20211103,20220118,B5.TIF
14744,bafybeibzs7vi2zvvnntj2v5ixxutrxi73b6jwyki7knza...,buckets/uofm-data1/landsat9-c2-l1/20211101/LC0...,baga6ea4seaqbofbcih54nxvtj3xkfporf2llpgsbvjwjn...,LC09_L1GT_026028_20211101_20220118_02_T2_B5.TIF,LC09_L1GT_026028_20211101_20220118_02_T2,026,028,20211101,20220118,B5.TIF
16901,bafybeifrqfyfbzmda7uq37icjdgreueraiq76tloo42np...,buckets/uofm-data1/landsat9-c2-l1/20211212/LC0...,baga6ea4seaqmubpon3owl7yvolm5npal7f4cwouofjivu...,LC09_L1TP_010028_20211212_20220120_02_T1_B5.TIF,LC09_L1TP_010028_20211212_20220120_02_T1,010,028,20211212,20220120,B5.TIF
17367,bafybeid5y5izd4hfjccm4evuzuio4ttdukmtbo5zyp3q3...,buckets/uofm-data1/landsat9-c2-l1/20220224/LC0...,baga6ea4seaqmjyo53rpct32b3ussbszadshww3pfozx7f...,LC09_L1TP_032028_20220224_20220224_02_T1_B5.TIF,LC09_L1TP_032028_20220224_20220224_02_T1,032,028,20220224,20220224,B5.TIF
45539,bafybeicpcfosz3xc33iovrk2z7gcf5jwdf7hsihxuxuiz...,buckets/uofm-data1/landsat9-c2-l1/20211104/LC0...,baga6ea4seaql7rcny2hno3w6uszgm5rgdx3qgp2mvqnvb...,LC09_L1TP_029028_20211104_20220118_02_T1_B5.TIF,LC09_L1TP_029028_20211104_20220118_02_T1,029,028,20211104,20220118,B5.TIF
50790,bafybeidpw5n4nbjsbmrsqplkjd4n3wuq7o2q7y7goem4r...,buckets/uofm-data1/landsat9-c2-l1/20220525/LC0...,baga6ea4seaqm6p4sdrr5q73i5f5k27m3c7fhycswbq3kg...,LC09_L1GT_022028_20220525_20220526_02_T2_B5.TIF,LC09_L1GT_022028_20220525_20220526_02_T2,022,028,20220525,20220526,B5.TIF
56118,bafybeicpo2i2ucrr6d2bpjmawob6dhkusyp2nftvfhk2d...,buckets/uofm-data1/landsat9-c2-l1/20211224/LC0...,baga6ea4seaqoi2mpu3jdrp4o7qmklokfgcffeywbiygn2...,LC09_L1GT_046028_20211224_20220121_02_T2_B5.TIF,LC09_L1GT_046028_20211224_20220121_02_T2,046,028,20211224,20220121,B5.TIF
65886,bafybeicnvcfloougj2sivtpnmpuza4xmofhag5qr5hf4h...,buckets/uofm-data1/landsat9-c2-l1/20211113/LC0...,baga6ea4seaqf4razpveevjivpxaxbakn6q32o7b5u6fgc...,LC09_L1TP_040028_20211113_20220119_02_T1_B5.TIF,LC09_L1TP_040028_20211113_20220119_02_T1,040,028,20211113,20220119,B5.TIF
74741,bafybeibq77e3ceakyxc54it5er5cvcfi5przitrssulaw...,buckets/uofm-data1/landsat9-c2-l1/20211031/LC0...,baga6ea4seaqa3xbb2stlxmqmttdvekiasnhvrwgwddugd...,LC09_L1TP_035028_20211031_20220118_02_T1_B5.TIF,LC09_L1TP_035028_20211031_20220118_02_T1,035,028,20211031,20220118,B5.TIF
80279,bafybeie4vipu64zy2m7k677ls3slkkrxfu6cowznlndhk...,buckets/uofm-data1/landsat9-c2-l1/20211101/LC0...,baga6ea4seaqm7of3acq6pmsesqdt7gf4zu7a5rs7l7cz3...,LC09_L1TP_042028_20211101_20220118_02_T1_B5.TIF,LC09_L1TP_042028_20211101_20220118_02_T1,042,028,20211101,20220118,B5.TIF
89549,bafybeidn3pjzqweo3onfrrsrh4kz434zw2qrsx5l32c4c...,buckets/uofm-data1/landsat9-c2-l1/20211104/LC0...,baga6ea4seaqd22m24zddfecvu5m6sf3sfvdeijstk3xsm...,LC09_L1TP_013028_20211104_20220118_02_T1_B5.TIF,LC09_L1TP_013028_20211104_20220118_02_T1,013,028,20211104,20220118,B5.TIF
102213,bafybeigi7pxiluziya6egv5zrpeippv4djzslq3axdmq5...,buckets/uofm-data1/landsat9-c2-l1/20211216/LC0...,baga6ea4seaqmy536qjkllke2jxesfc7a3zwcxt2vhls2y...,LC09_L1TP_038028_20211216_20220121_02_T1_B5.TIF,LC09_L1TP_038028_20211216_20220121_02_T1,038,028,20211216,20220121,B5.TIF
103345,bafybeifegd3d6pzxasw6vifdi7njwpamoft6etj4u6pjp...,buckets/uofm-data1/landsat9-c2-l1/20211213/LC0...,baga6ea4seaqd6whwfufhy25a2tw5r2vlhabvt7eo4qa4i...,LC09_L1GT_033028_20211213_20220120_02_T2_B5.TIF,LC09_L1GT_033028_20211213_20220120_02_T2,033,028,20211213,20220120,B5.TIF
104954,bafybeicq7bqnedncwkz3nhtcshssncdpyftvkzfnzkghl...,buckets/uofm-data1/landsat9-c2-l1/20211104/LC0...,baga6ea4seaqewt67u6crkixr2xsplu7uqiyqvyntziik2...,LC09_L1TP_045028_20211104_20220118_02_T1_B5.TIF,LC09_L1TP_045028_20211104_20220118_02_T1,045,028,20211104,20220118,B5.TIF
108149,bafybeieqrmo3rwcxmha5o3q2jy3vc2zfwpvwji6b3hssa...,buckets/uofm-data1/landsat9-c2-l1/20220226/LC0...,baga6ea4seaqh6zhps24i3athah5rkadhvgy47vpevg666...,LC09_L1TP_030028_20220226_20220226_02_T1_B5.TIF,LC09_L1TP_030028_20220226_20220226_02_T1,030,028,20220226,20220226,B5.TIF
108999,bafybeicc4zns2goa5kmdork35p2tzvxcnpp7oc2l4sxx3...,buckets/uofm-data1/landsat9-c2-l1/20220228/LC0...,baga6ea4seaqevtvra5aw4sdvw35utxjzdtvfpd2hokhrw...,LC09_L1GT_044028_20220228_20220228_02_T2_B5.TIF,LC09_L1GT_044028_20220228_20220228_02_T2,044,028,20220228,20220228,B5.TIF
127226,bafybeifkfro6prhug22pvsu2o7ju5ccloet5v4xuizjhx...,buckets/uofm-data1/landsat9-c2-l1/20220227/LC0...,baga6ea4seaqcejzb6vfal2bt3u2mc7h5osdiczw4yfogf...,LC09_L1TP_037028_20220227_20220227_02_T1_B5.TIF,LC09_L1TP_037028_20220227_20220227_02_T1,037,028,20220227,20220227,B5.TIF
131793,bafybeibygdxwnmqzcy6iirye27o32gj6mnrjf65fn2ft3...,buckets/uofm-data1/landsat9-c2-l1/20220227/LC0...,baga6ea4seaqkboli4ks5ehrqy7lfeo6zemuze2yvy3zdt...,LC09_L1TP_021028_20220227_20220227_02_T1_B5.TIF,LC09_L1TP_021028_20220227_20220227_02_T1,021,028,20220227,20220227,B5.TIF
132596,bafybeih2eirkjxyqsfobws4jclxtajrvo4qqz2skrmt5k...,buckets/uofm-data1/landsat9-c2-l1/20220120/LC0...,baga6ea4seaqgbjfjth7w6zyqqp24vjv2pq2qnqz3dqrrb...,LC09_L1GT_043028_20220120_20220120_02_T2_B5.TIF,LC09_L1GT_043028_20220120_20220120_02_T2,043,028,20220120,20220120,B5.TIF
148826,bafybeigpwo22hgdo7lmwxgigdmggzpcm5vvs4cvfr3zf6...,buckets/uofm-data1/landsat9-c2-l1/20220228/LC0...,baga6ea4seaqihterk4nkqv77eyc5rgvtnyow44ltpy62c...,LC09_L1TP_012028_20220228_20220228_02_T1_B5.TIF,LC09_L1TP_012028_20220228_20220228_02_T1,012,028,20220228,20220228,B5.TIF
149718,bafybeifm4p56arl4yiiay3xrdublccydcre47t7uuhsv3...,buckets/uofm-data1/landsat9-c2-l1/20211111/LC0...,baga6ea4seaqfgqzlih5c2zeebgjq52pgmw3chihxxczkc...,LC09_L1TP_011028_20211111_20220119_02_T1_B5.TIF,LC09_L1TP_011028_20211111_20220119_02_T1,011,028,20211111,20220119,B5.TIF
153125,bafybeibxjko2thxhtjq6l4dhuyscjnhgz6u53ndtq4kyn...,buckets/uofm-data1/landsat9-c2-l1/20220228/LC0...,baga6ea4seaqdowhqdoiy4pkgrexdi2lq7w24zs5tvxu74...,LC09_L1TP_028028_20220228_20220228_02_T2_B5.TIF,LC09_L1TP_028028_20220228_20220228_02_T2,028,028,20220228,20220228,B5.TIF
158200,bafybeidck3z4uw2fu53g35anlwdn6piriwtdhfmjqcekx...,buckets/uofm-data1/landsat9-c2-l1/20211110/LC0...,baga6ea4seaqfgqzlih5c2zeebgjq52pgmw3chihxxczkc...,LC09_L1TP_036028_20211110_20220119_02_T1_B5.TIF,LC09_L1TP_036028_20211110_20220119_02_T1,036,028,20211110,20220119,B5.TIF
168818,bafybeihhspi7s7vpujlhhpjeci3ydhrsyb23lfjeaekfu...,buckets/uofm-data1/landsat9-c2-l1/20211221/LC0...,baga6ea4seaqfearc7r7qsgi7ligwee7ljsknkarfww5p7...,LC09_L1GT_025028_20211221_20220121_02_T2_B5.TIF,LC09_L1GT_025028_20211221_20220121_02_T2,025,028,20211221,20220121,B5.TIF
170051,bafybeihtv3yr3kway3rwg7ucxgbiag4ubwhpmygmdinuv...,buckets/uofm-data1/landsat9-c2-l1/20211111/LC0...,baga6ea4seaqk2os56taxtl6w6auprpwmj4yzy36scm26m...,LC09_L1GT_027028_20211111_20220119_02_T2_B5.TIF,LC09_L1GT_027028_20211111_20220119_02_T2,027,028,20211111,20220119,B5.TIF
173329,bafybeieiqbflw3zc3zdtqoaeqbssikctrlt4rnagdjdmo...,buckets/uofm-data1/landsat9-c2-l1/20211205/LC0...,baga6ea4seaqmnshvsjq4qug6ekvqkpehhu5sugob4ta73...,LC09_L1TP_041028_20211205_20220120_02_T1_B5.TIF,LC09_L1TP_041028_20211205_20220120_02_T1,041,028,20211205,20220120,B5.TIF
178064,bafybeian7nkaklkfj4arspff57jmaujp4jhqtupkxgmkz...,buckets/uofm-data1/landsat9-c2-l1/20211122/LC0...,baga6ea4seaqdqoi3s33rwzyjw4pv5snr3noyc3xmdbdqt...,LC09_L1TP_034028_20211122_20220120_02_T1_B5.TIF,LC09_L1TP_034028_20211122_20220120_02_T1,034,028,20211122,20220120,B5.TIF
178508,bafybeidkfjiiy6o4y2j6id7kn64esue2oixqn4pirkagv...,buckets/uofm-data1/landsat9-c2-l1/20211113/LC0...,baga6ea4seaqdv3uhcwkpxvdzpog6qvf2yntvcqzoo5cnq...,LC09_L1TP_024028_20211113_20220119_02_T1_B5.TIF,LC09_L1TP_024028_20211113_20220119_02_T1,024,028,20211113,20220119,B5.TIF
184660,bafybeicfji4fyqwmhhhzixird2j5gxyjlf7wjcmv7joeh...,buckets/uofm-data1/landsat9-c2-l1/20211222/LC0...,baga6ea4seaqabxu7xgn4shrevmam4eleifhxhsc52wups...,LC09_L1GT_048028_20211222_20220121_02_T2_B5.TIF,LC09_L1GT_048028_20211222_20220121_02_T2,048,028,20211222,20220121,B5.TIF
185454,bafybeig5wlgdfib4lyo3jldmfwaurhi3ovnu2doihkjpd...,buckets/uofm-data1/landsat9-c2-l1/20211215/LC0...,baga6ea4seaqmmpbaliy2a7nh3fciyov2er3giimqt5vre...,LC09_L1TP_031028_20211215_20220120_02_T1_B5.TIF,LC09_L1TP_031028_20211215_20220120_02_T1,031,028,20211215,20220120,B5.TIF
185899,bafybeidmlgycomnlyfks2rjqqjm2fp247wq4ogujcq775...,buckets/uofm-data1/landsat9-c2-l1/20211215/LC0...,baga6ea4seaqes6zhnt2sfg6wr22uzoputn6mhfcsqzndy...,LC09_L1GT_047028_20211215_20220120_02_T2_B5.TIF,LC09_L1GT_047028_20211215_20220120_02_T2,047,028,20211215,20220120,B5.TIF

In [17]:
scene_cnt = df.groupby("sceneid").Asset.count().reset_index()

In [18]:
scene_cnt = scene_cnt.set_axis(["sceneid", "cnt"], axis=1)

In [19]:
cont_us_B5_cnt = cont_us_B5.merge(scene_cnt, on=["sceneid"], how="left").sort_values(
    ["sceneid", "cnt"], ascending=[True, False]
)
cont_us_B5_sel = cont_us_B5_cnt.drop_duplicates(subset=["PPP", "RRR"], keep="first")

In [20]:
cont_us_B5_sel["Filepath"].str.replace("buckets/", "piknik:").to_csv(
    "B5_path.txt", index=False, header=False
)

In [21]:
cont_us_B5_sel[["FileCID", "Filepath", "PieceCID"]].to_csv(
    "../../../data/FileCID_Filepath_selected_b5.csv", index=False
)

In [22]:
cont_us_B5_sel["filename"].to_csv("B5_filename.txt", index=False, header=False)

In [23]:
df_sel = df[df.sceneid.isin(cont_us_B5_sel.sceneid)]

In [24]:
df_sel["Filepath"].str.replace("buckets/", "piknik:").to_csv(
    "All_path.txt", index=False, header=False
)

In [25]:
df_sel[["FileCID", "Filepath", "PieceCID"]].to_csv(
    "../../../data/FileCID_Filepath_selected.csv", index=False
)

In [26]:
df_sel.shape

(10956, 10)

In [27]:
## verify existence of stac.json

In [28]:
def check_file_exists(row):
    import os

    file_path = f"../../data/stac/landsat-c2l1/json/{str(row['AcqDate'])}/{str(row['sceneid'])}_stac.json"
    return os.path.exists(file_path)

In [29]:
cont_us_B5_sel["stac_exists"] = cont_us_B5_sel.apply(check_file_exists, axis=1)

/tmp/ipykernel_131779/18014606.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cont_us_B5_sel['stac_exists'] = cont_us_B5_sel.apply(check_file_exists, axis=1)

In [68]:
cont_us_B5_sel

,FileCID,Filepath,PieceCID,filename,sceneid,PPP,RRR,AcqDate,PrsDate,Asset,cnt,stac_exists
710,bafybeia5y5bnscwjycvth44otp3mpd7r7rlw2oveobp6t...,buckets/uofm-data1/landsat9-c2-l1/20211228/LC0...,baga6ea4seaqhbeonuh7fe62v6hlyiowkgdvpqwp7nklrr...,LC09_L1GT_010028_20211228_20220121_02_T2_B5.TIF,LC09_L1GT_010028_20211228_20220121_02_T2,010,028,20211228,20220121,B5.TIF,24,True
860,bafybeiahy2pux3c3veuwidezz3voujl6mysv6lbhu64ud...,buckets/uofm-data1/landsat9-c2-l1/20211228/LC0...,baga6ea4seaqbgn4axr2mcxmwgbtd32krjr46atizuu35r...,LC09_L1GT_010029_20211228_20220121_02_T2_B5.TIF,LC09_L1GT_010029_20211228_20220121_02_T2,010,029,20211228,20220121,B5.TIF,24,True
819,bafybeic4dip65ilzco32qritbgwrmf5efpxkobvg27ayy...,buckets/uofm-data1/landsat9-c2-l1/20211228/LC0...,baga6ea4seaqdi5ifuv325xt55ixyrmgb3sbcs5zz5abgn...,LC09_L1GT_010030_20211228_20220121_02_T2_B5.TIF,LC09_L1GT_010030_20211228_20220121_02_T2,010,030,20211228,20220121,B5.TIF,24,True
6279,bafybeictfdhmaowpntfh3gsmhu6xb2xfdgvhyiy55e6xu...,buckets/uofm-data1/landsat9-c2-l1/20220325/LC0...,baga6ea4seaqdcljnj7i3pdrdry6kypxl6g2rujfkhyy4x...,LC09_L1GT_011027_20220325_20220325_02_T2_B5.TIF,LC09_L1GT_011027_20220325_20220325_02_T2,011,027,20220325,20220325,B5.TIF,24,True
6257,bafybeibkmv2luzlmxpf7gdgqepbux57mg5xm62cxvos53...,buckets/uofm-data1/landsat9-c2-l1/20211116/LC0...,baga6ea4seaqpl4itz2x4rxyycmisf42z3owaq3er5svma...,LC09_L1GT_011028_20211116_20220119_02_T2_B5.TIF,LC09_L1GT_011028_20211116_20220119_02_T2,011,028,20211116,20220119,B5.TIF,24,True
...,...,...,...,...,...,...,...,...,...,...,...,...
4058,bafybeifvupuhs77vtjq5rmcf5ujoaa2sdt5ujfgddowse...,buckets/uofm-data1/landsat9-c2-l1/20211104/LC0...,baga6ea4seaqdwkdobn3c2aim6pxfnmcybteug53fe5m7r...,LC09_L1TP_045032_20211104_20220118_02_T1_B5.TIF,LC09_L1TP_045032_20211104_20220118_02_T1,045,032,20211104,20220118,B5.TIF,24,True
4074,bafybeid5u72cvp25ftnyv6kjonlmsag5yojblktwzbdko...,buckets/uofm-data1/landsat9-c2-l1/20211104/LC0...,baga6ea4seaqbibxzmbqo2uefpm4jlr27swla5dwnog27b...,LC09_L1TP_045033_20211104_20220118_02_T1_B5.TIF,LC09_L1TP_045033_20211104_20220118_02_T1,045,033,20211104,20220118,B5.TIF,24,True
4419,bafybeicwom6b6j4f6qlqbyzgngtrc57vnynww2u2fbdjq...,buckets/uofm-data1/landsat9-c2-l1/20211104/LC0...,baga6ea4seaqa7yb62r37irjn66h3xvs7ay4s3apga4okz...,LC09_L1TP_045034_20211104_20220118_02_T1_B5.TIF,LC09_L1TP_045034_20211104_20220118_02_T1,045,034,20211104,20220118,B5.TIF,24,True
4824,bafybeigkaa7bkrsyraiahmcab34xo3h3pp5oxoy62d5mo...,buckets/uofm-data1/landsat9-c2-l1/20211109/LC0...,baga6ea4seaqf4jh4q6arvetpuegtddsv5mhjqq2bxfbms...,LC09_L1TP_046026_20211109_20220119_02_T1_B5.TIF,LC09_L1TP_046026_20211109_20220119_02_T1,046,026,20211109,20220119,B5.TIF,24,True
3461,bafybeihmyii3xumpjxve3vvp3euskpxy2vnmcr6zb3snf...,buckets/uofm-data1/landsat9-c2-l1/20211109/LC0...,baga6ea4seaqf4jh4q6arvetpuegtddsv5mhjqq2bxfbms...,LC09_L1TP_046027_20211109_20220119_02_T1_B5.TIF,LC09_L1TP_046027_20211109_20220119_02_T1,046,027,20211109,20220119,B5.TIF,24,True

In [73]:
df_sel.query('RRR=="028" & PPP=="010"')

,FileCID,Filepath,PieceCID,filename,sceneid,PPP,RRR,AcqDate,PrsDate,Asset
324478,bafybeiae22tufquhom2ablmtn6epohscs7nvrifoltrwg...,buckets/uofm-data1/landsat9-c2-l1/20211228/LC0...,baga6ea4seaqnc5oayxi3j3cwxqpskdrt2klfbxnvmuvol...,LC09_L1GT_010028_20211228_20220121_02_T2_VAA.TIF,LC09_L1GT_010028_20211228_20220121_02_T2,010,028,20211228,20220121,VAA.TIF
330736,bafkreih7ax53e3y3ckvooh44pivlpitxlilf645cgpuml...,buckets/uofm-data1/landsat9-c2-l1/20211228/LC0...,baga6ea4seaqnjsl7fzsqdahuisnub5skfvbi7s44wb3to...,LC09_L1GT_010028_20211228_20220121_02_T2_stac....,LC09_L1GT_010028_20211228_20220121_02_T2,010,028,20211228,20220121,stac.json
330777,bafybeick7qp3tutuvypwow7qtlpbgj42jc773chk4ifuq...,buckets/uofm-data1/landsat9-c2-l1/20211228/LC0...,baga6ea4seaqlxyqeqnbt32f676xhhagh3kjs2lunknqew...,LC09_L1GT_010028_20211228_20220121_02_T2_B3.TIF,LC09_L1GT_010028_20211228_20220121_02_T2,010,028,20211228,20220121,B3.TIF
330882,bafkreigqgnkhkkft2d6ufgzi2gti3xbanueekg6rhrkiu...,buckets/uofm-data1/landsat9-c2-l1/20211228/LC0...,baga6ea4seaqnjsl7fzsqdahuisnub5skfvbi7s44wb3to...,LC09_L1GT_010028_20211228_20220121_02_T2_MTL.txt,LC09_L1GT_010028_20211228_20220121_02_T2,010,028,20211228,20220121,MTL.txt
332112,bafkreiermgqheprxs5lbcxiymon2ndrczbtbkxeaszxe2...,buckets/uofm-data1/landsat9-c2-l1/20211228/LC0...,baga6ea4seaqnjsl7fzsqdahuisnub5skfvbi7s44wb3to...,LC09_L1GT_010028_20211228_20220121_02_T2_thumb...,LC09_L1GT_010028_20211228_20220121_02_T2,010,028,20211228,20220121,thumb_large.jpeg
332216,bafybeie4m7e2jkc2cjoryaz5op6lwuzfbpx2bjgb7ps7d...,buckets/uofm-data1/landsat9-c2-l1/20211228/LC0...,baga6ea4seaqeixln6ge4qs74q4nv44iyvwpgbxazu4atf...,LC09_L1GT_010028_20211228_20220121_02_T2_B11.TIF,LC09_L1GT_010028_20211228_20220121_02_T2,010,028,20211228,20220121,B11.TIF
332282,bafybeigkiludlo27hxmjkrxbq3vz56rjzpo7x6dk3uzil...,buckets/uofm-data1/landsat9-c2-l1/20211228/LC0...,baga6ea4seaqeiehzg7rj2fjlnabjqzgpkgqhmcmkcoutg...,LC09_L1GT_010028_20211228_20220121_02_T2_B6.TIF,LC09_L1GT_010028_20211228_20220121_02_T2,010,028,20211228,20220121,B6.TIF
333355,bafybeieqkxx2vkcolfxclqvyalqdi2opggsh45tdo2pco...,buckets/uofm-data1/landsat9-c2-l1/20211228/LC0...,baga6ea4seaqlxyqeqnbt32f676xhhagh3kjs2lunknqew...,LC09_L1GT_010028_20211228_20220121_02_T2_B2.TIF,LC09_L1GT_010028_20211228_20220121_02_T2,010,028,20211228,20220121,B2.TIF
333479,bafybeiegi7lcqqn6pj4im6cdy5z2y5gm5xu5k7tmrkiqg...,buckets/uofm-data1/landsat9-c2-l1/20211228/LC0...,baga6ea4seaqd4qdcssfhbtwfxvk4hbx57cgma4pxdm6u5...,LC09_L1GT_010028_20211228_20220121_02_T2_B7.TIF,LC09_L1GT_010028_20211228_20220121_02_T2,010,028,20211228,20220121,B7.TIF
583037,bafybeihswdmcflfwurrfssvgljr6s4vay5xre2oxfnwvq...,buckets/uofm-data1/landsat9-c2-l1/20211228/LC0...,baga6ea4seaqeixln6ge4qs74q4nv44iyvwpgbxazu4atf...,LC09_L1GT_010028_20211228_20220121_02_T2_B10.TIF,LC09_L1GT_010028_20211228_20220121_02_T2,010,028,20211228,20220121,B10.TIF
583109,bafybeibs54awl77ll7rn666rp5p4hd3metobnrflraakz...,buckets/uofm-data1/landsat9-c2-l1/20211228/LC0...,baga6ea4seaqaurpcnzevdhfxnviqr2urwnjrpmaphzqcc...,LC09_L1GT_010028_20211228_20220121_02_T2_B9.TIF,LC09_L1GT_010028_20211228_20220121_02_T2,010,028,20211228,20220121,B9.TIF
584143,bafybeia5o6vithoztcdpr3dj5awgwrchpojy66whgwr2j...,buckets/uofm-data1/landsat9-c2-l1/20211228/LC0...,baga6ea4seaqnc5oayxi3j3cwxqpskdrt2klfbxnvmuvol...,LC09_L1GT_010028_20211228_20220121_02_T2_VZA.TIF,LC09_L1GT_010028_20211228_20220121_02_T2,010,028,20211228,20220121,VZA.TIF
584171,bafybeig2ekfr5aniypgyjyun2jy2txe6z2lywwdu6ygmw...,buckets/uofm-data1/landsat9-c2-l1/20211228/LC0...,baga6ea4seaqere53gw2edsk3spubfkljut4x3m6ybz2wv...,LC09_L1GT_010028_20211228_20220121_02_T2_B8.TIF,LC09_L1GT_010028_20211228_20220121_02_T2,010,028,20211228,20220121,B8.TIF
584180,bafkreicnmyg5k56pwdc54477emvgrpza2guy2cr2pelnu...,buckets/uofm-data1/landsat9-c2-l1/20211228/LC0...,baga6ea4seaqnjsl7fzsqdahuisnub5skfvbi7s44wb3to...,LC09_L1GT_010028_20211228_20220121_02_T2_MTL.xml,LC09_L1GT_010028_20211228_20220121_02_T2,010,028,20211228,20220121,MTL.xml
584186,bafybeia5y5bnscwjycvth44otp3mpd7r7rlw2oveobp6t...,buckets/uofm-data1/landsat9-c2-l1/20211228/LC0...,baga6ea4seaqhbeonuh7fe62v6hlyiowkgdvpqwp7nklrr...,LC09_L1GT_010028_20211228_20220121_02_T2_B5.TIF,LC09_L1GT_010028_20211228_20220121_02_T2,010,028,20211228,20220121,B5.TIF
584198,bafybeieq3nocpavozzlwpipqbjexd5aguxdkbz7t23rft...,buckets/uofm-data1/landsat9-c2-l1/20211228/LC0...,baga6ea4seaqnc5oayxi3j3cwxqpskdrt2klfbxnvmuvol...,LC09_L1GT_010028_20211228_20220121_02_T2_SZA.TIF,LC09_L1GT_010028_20211228_20220121_02_T2,010,028,20211228,20220121,SZA.TIF
584205,bafybeib2pedsazpv4va4zc47mcxbao3i7bm262rtlcd2e...,buckets/uofm-data1/landsat9-c2-l1/20211228/LC0...,baga6ea4seaqnc5oayxi3j3cwxqpskdrt2klfbxnvmuvol...,LC09_L1GT_010028_20211228_20220121_02_T2_QA_PI...,LC09_L1GT_010028_20211228_20220121_02_T2,010,028,20211228,20220121,QA_PIXEL.TIF
584206,bafkreiem7c4a2glzc3gcjxqyuqhgtyvkwkctv7l7nqzs7...,buckets/uofm-data1/landsat9-c2-l1/20211228/LC0...,baga6ea4seaqnjsl7fzsqdahuisnub5skfvbi7s44wb3to...,LC09_L1GT_010028_20211228_20220121_02_T2_thumb...,LC09_L1GT_010028_20211228_20220121_02_T2,010,028,20211228,20220121,thumb_small.jpeg
584223,bafybeigjfu22r5aq465y2fivrzdecokvj5es3xejaq4ob...,buckets/uofm-data1/landsat9-c2-l1/20211228/LC0...,baga6ea4seaqf2dq2fuwul6d3elpgwcysl3ovspd7r3ghf...,LC09_L1GT_010028_20211228_20220121_02_T2_B1.TIF,LC09_L1GT_010028_20211228_20220121_02_T2,010,028,20211228,20220121,B1.TIF
584225,bafkreibloeziezef32yydka6kli6bjz7yu5g5engrfbo7...,buckets/uofm-data1/landsat9-c2-l1/20211228/LC0...,baga6ea4seaqnjsl7fzsqdahuisnub5skfvbi7s44wb3to...,LC09_L1GT_010028_20211228_20220121_02_T2_QA_RA...,LC09_L1GT_010028_20211228_20220121_02_T2,010,028,20211228,20220121,QA_RADSAT.TIF
584243,bafkreiazkreyhvcdok4f7rfezuf2cq6wctfmczlhwyujc...,buckets/uofm-data1/landsat9-c2-l1/20211228/LC0...,baga6ea4seaqnjsl7fzsqdahuisnub5skfvbi7s44wb3to...,LC09_L1GT_010028_20211228_20220121_02_T2_MTL.json,LC09_L1GT_010028_20211228_20220121_02_T2,010,028,20211228,20220121,MTL.json
584248,bafkreigua5zdhhhbvle7oog5jdhatcdehw37xe56ownea...,buckets/uofm-data1/landsat9-c2-l1/20211228/LC0...,baga6ea4seaqnjsl7fzsqdahuisnub5skfvbi7s44wb3to...,LC09_L1GT_010028_20211228_20220121_02_T2_ANG.txt,LC09_L1GT_010028_20211228_20220121_02_T2,010,028,20211228,20220121,ANG.txt
584252,bafybeigopfldwuhltbnuxjlnqyc6imlamg2y3kxzptcv2...,buckets/uofm-data1/landsat9-c2-l1/20211228/LC0...,baga6ea4seaqnc5oayxi3j3cwxqpskdrt2klfbxnvmuvol...,LC09_L1GT_010028_20211228_20220121_02_T2_SAA.TIF,LC09_L1GT_010028_20211228_20220121_02_T2,010,028,20211228,20220121,SAA.TIF
584276,bafybeic7fbruebnqah7p3blnxt3gvtl3thgw7pll23pq6...,buckets/uofm-data1/landsat9-c2-l1/20211228/LC0...,baga6ea4seaqeiehzg7rj2fjlnabjqzgpkgqhmcmkcoutg...,LC09_L1GT_010028_20211228_20220121_02_T2_B4.TIF,LC09_L1GT_010028_20211228_20220121_02_T2,010,028,20211228,20220121,B4.TIF

In [30]:
cont_us_B5_sel[cont_us_B5_sel.stac_exists].shape == cont_us_B5_sel.shape

True

In [ ]:
# inflate web3 information (df_sel) into stac.json

In [31]:
# Initialize an empty dictionary to hold the result
result = {}

# Group the DataFrame by 'sceneid'
for sceneid, group_data in df_sel.groupby("sceneid"):
    # Initialize a dictionary for this 'sceneid'
    scene_dict = {}

    # Iterate through the group data
    for index, row in group_data.iterrows():
        filename, cid = row["filename"], row["FileCID"]

        # Initialize a list for this filename if it doesn't exist
        if filename not in scene_dict:
            scene_dict[filename] = []

        # Add the cid to the list for this filename
        scene_dict[filename].append(cid)

    # Add this scene_dict to the overall result
    result[sceneid] = scene_dict

In [ ]:
result

In [122]:
# loop to enrich stac


def enrich_web3(row):
    import json
    import os
    import urllib.parse

    input_stac_path = f"../../data/stac/landsat-c2l1/json/{str(row['AcqDate'])}/{str(row['sceneid'])}_stac.json"
    output_stac_path = f"../../data/stac/landsat-c2l1/web3_enriched_json/{str(row['sceneid'])}_stac.json"

    profile = result[row["sceneid"]]
    with open(input_stac_path) as input_file:
        stac_data = json.load(input_file)

    for asset_name, asset_data in stac_data["assets"].items():
        # print(asset_data)
        href = asset_data["href"]
        file_name = os.path.basename(urllib.parse.urlparse(href).path)
        if asset_name == "index" or "alternate" not in asset_data:
            if asset_name != "index":
                print("no alternate for", asset_name)
            continue
        if "IPFS" not in asset_data["alternate"]:
            asset_data["alternate"]["IPFS"] = {}
        # print(file_name)
        if file_name in profile:
            asset_data["alternate"]["IPFS"]["href"] = f"ipfs://{profile[file_name][0]}"
            # print(profile)
        else:
            print(f"FileCID not found for asset: {asset_name}")
    with open(output_stac_path, "w") as output_file:
        json.dump(stac_data, output_file, indent=4)
    return True

In [40]:
os.getcwd()

'/gpfs/data1/oshangp/easier/easier/code/Pynotebooks'

In [41]:
from dotenv import load_dotenv
import os

load_dotenv()
ipfs_binary = os.getenv("ipfs_binary")

In [42]:
ipfs_binary

'/gpfs/data1/oshangp/easier/textile/kubo/ipfs'

In [61]:
# loop to enrich stac


def compute_cid(file_path):
    import subprocess

    cid = (
        subprocess.check_output(
            [ipfs_binary, "add", "-qn", "--cid-version", "1", file_path]
        )
        .decode()
        .strip()
    )
    return cid


def enrich_dual_web3(row):
    import json
    import os
    import urllib.parse
    import pathlib

    input_stac_path = f"../../data/stac/landsat-c2l1/json/{str(row['AcqDate'])}/{str(row['sceneid'])}_stac.json"
    output_stac_path = f"../../data/stac/landsat-c2l1/web3_enriched_json/{str(row['sceneid'])}_stac.json"

    profile = result[row["sceneid"]]

    with open(input_stac_path) as input_file:
        stac_data = json.load(input_file)

    for asset_name, asset_data in stac_data["assets"].items():
        # print(asset_data)
        href = asset_data["href"]
        file_name = os.path.basename(urllib.parse.urlparse(href).path)
        file_path = f"../../data/landsat/piknik/{str(file_name)}"
        if asset_name == "index" or "alternate" not in asset_data:
            if asset_name != "index":
                print("no alternate for", asset_name)
            continue
        if pathlib.Path(file_path).is_file():
            cid = compute_cid(file_path)
            if "IPFS" not in asset_data["alternate"]:
                asset_data["alternate"]["IPFS"] = {}
            asset_data["alternate"]["IPFS"]["href"] = f"ipfs://{cid}"
        else:
            print(f"File not found for asset: {asset_name}")

        if "Filecoin" not in asset_data["alternate"]:
            asset_data["alternate"]["Filecoin"] = {}
        # print(file_name)
        if file_name in profile:
            asset_data["alternate"]["Filecoin"][
                "href"
            ] = f"ipfs://{profile[file_name][0]}"
            asset_data["alternate"]["Filecoin"]["storage:platform"] = "PiKNiK"
            # print(profile)
        else:
            print(f"Filecoin CID not found for asset: {asset_name}")
    with open(output_stac_path, "w") as output_file:
        json.dump(stac_data, output_file, indent=4)
    return True

In [ ]:
cont_us_B5_sel.apply(enrich_dual_web3, axis=1)

File not found for asset: thumbnail
Filecoin CID not found for asset: thumbnail
File not found for asset: reduced_resolution_browse
Filecoin CID not found for asset: reduced_resolution_browse
File not found for asset: MTL.json
Filecoin CID not found for asset: MTL.json
File not found for asset: thumbnail
Filecoin CID not found for asset: thumbnail
File not found for asset: reduced_resolution_browse
Filecoin CID not found for asset: reduced_resolution_browse
File not found for asset: thumbnail
Filecoin CID not found for asset: thumbnail
File not found for asset: reduced_resolution_browse
Filecoin CID not found for asset: reduced_resolution_browse